TAMAPI-2248 Add regular Cassandra repair
TurbineAnalytics/docker-spark-cassandra pull request #15
Opened 2018-10-10 11:37 UTC by wrobel7

Before merge it is required to create environment variable `REPAIRING_NODE=true` on a SINGLE CASSANDRA NODE on every environment (test, dev, prod)

2018-10-18 08:43 UTC, MichalOlejniczak requested changes
Była rozmowa. Odnośnie lokalizacji plików, nazewnictwa, tego jak odpalać crony i ich częstotliwości.

Plus labels, milestones itd. itp.

2018-10-18 12:44 UTC, alach1 requested changes
cron i skrypty związane z repai nie powinny być w folderze backup, zróbmy nowy folder `repair`
i równocześnie `/backup/crontab.txt` niech będzie chyba w głównym folderze

2018-10-19 11:04 UTC, wrobel7 commented
@alach1 Poprawiłem Twoje uwagi

2018-10-22 08:25 UTC, alach1 submitted a review, later dismissed

2018-10-25 15:14 UTC, MichalOlejniczak requested changes

2018-10-25 15:14 UTC, MichalOlejniczak commented on cassandra-configurator.sh
> +    ./backup/setup_crone_job.sh
`setup_crone_job` bym wyniósł wyżej, żeby nie był ściśle z folderem backup powiązany jeśli ustawia też dla repair

2018-10-25 15:14 UTC, MichalOlejniczak commented on repair/cassandra_repair_crontab.txt
> +#Cassandra incremental node repair job, run from Monday to Saturday at 2 a.m.
a nie rozmawialiśmy, żeby incremental robił się raz na tydzień?

2018-10-25 15:14 UTC, MichalOlejniczak commented on repair/cassandra_repair_crontab.txt
> +#Cassandra full node repair job, run on Sunday at 2 a.m.
a nie rozmawialiśmy, żeby full robił się raz na miesiąc?

2018-10-29 14:25 UTC, wrobel7 commented on cassandra-configurator.sh
> +    ./backup/setup_crone_job.sh
Done

2018-10-29 14:25 UTC, wrobel7 commented on repair/cassandra_repair_crontab.txt
> +#Cassandra incremental node repair job, run from Monday to Saturday at 2 a.m.
Done

2018-10-29 14:25 UTC, wrobel7 commented on repair/cassandra_repair_crontab.txt
> +#Cassandra full node repair job, run on Sunday at 2 a.m.
Done

2018-10-30 06:23 UTC, MichalOlejniczak approved these changes

2018-10-30 08:11 UTC, merged