Bugfix / TAMAPI-1572 cassandra tuning
TurbineAnalytics/docker-spark-cassandra pull request #3
Opened 2017-07-28 13:37 UTC by alach1

Zmiany w image cassandry:
- biblioteka jemalloc
- konfiguracja do metrics reporter
- base z Cassandry 3.5, Java Oracle 8
- memory dump do folderu: /var/log/cassandra

2017-07-29 21:51 UTC, emlagowski requested changes

2017-07-29 21:51 UTC, emlagowski commented on Dockerfile
> -    && apt-get install -y cron \
co z tym cronem? @MichalOlejniczak dodał to chyba do tworzenia backupów

2017-07-31 10:15 UTC, alach1 commented on Dockerfile
> -    && apt-get install -y cron \
Dzięki, przywróciłem net-tools i cron

2017-08-02 10:06 UTC, emlagowski requested changes

2017-08-02 10:06 UTC, emlagowski commented on .travis.yml
> +  - export DOCKER_HUB_REPO=turbineanalytics/
to powinno być w zmiennych `env` a nie tutaj za pomocą `export`

2017-08-02 14:19 UTC, emlagowski approved these changes

2017-08-02 14:21 UTC, merged